import Navigation from "./components/navigation/Navigation";
import "./globals.css";
//import { Space_Grotesk } from "next/font/google";

//const font = Space_Grotesk({ subsets: ["latin"], weight:[400, 700] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My 1st app with nextjs 13</title>
      </head>
      <body 
      //className={font.className}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
